name: "Deploy to Google Cloud Run"

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name : Google auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name : Google auth Docker
        run: gcloud auth configure-docker

      - name: 'Build Docker image'
        run: docker build -f ./Dockerfile -t eu.gcr.io/deploy-276111/breeding-calculator:${{ github.sha }} .

      - name: 'Push Docker image'
        run: docker push eu.gcr.io/deploy-276111/breeding-calculator:${{ github.sha }}

      - name: 'Install terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4

      - name: 'Deploy app'
        run: |
          cd terraform
          terraform init
          terraform apply -var-file=prod.tfvars -auto-approve
        env:
          TF_VAR_image_tag: ${{ github.sha }}
